version: '3'
services:
  rest:
    build:
        context: .
        dockerfile: Dockerfile
    image: rest
    container_name: rest
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    ports:
      - "3000:3000"
    volumes:
      - ".:/usr/src/app"
    networks:
      - app-network
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_DB=content
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
